
name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Only trigger when files in backend folder change

jobs:
  build:
    runs-on: self-hosted  # Ensure your runner is running

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json  # Cache npm modules inside backend

    - name: Install dependencies
      run: |
        cd backend
        npm ci  # or npm install if no package-lock.json

    - name: Build
      run: |
        cd backend
        npm run build --if-present

