name: frontend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: [self-hosted, frontend]
    environment: production  

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies & Build frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Clean workspace (free space)
      run: |
        rm -rf frontend/node_modules
        docker system prune -af || true
        docker volume prune -f || true
        docker builder prune -af || true

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -f frontend/Dockerfile -t ankitdockerd/frontend:latest frontend

    - name: Push Docker image
      run: docker push ankitdockerd/frontend:latest

    - name: Restart Frontend
      run: |
        pm2 restart frontend || pm2 start npm --name "frontend" -- start
